### ISSUE TITLE
conundrum's broken

### ISSUE THREAD

**Issue by agjmills** [jes/cntdnirc#1]
21:42:52 < Nick_Cntdn> joelr__: let's take a look...
21:42:53 < tinyhippo> unlimbers
21:42:53 < Nick_Cntdn>  U N L I M B E R S 
21:42:53 < Nick_Cntdn> It's the right answer! 10 points to joelr__
21:42:53 < Nick_Cntdn> tinyhippo: let's take a look...
21:42:54 < Nick_Cntdn>  U N L I M B E R S 
21:42:54 < Nick_Cntdn> It's the right answer! 10 points to tinyhippo
21:42:57 < Nick_Cntdn> tinyhippo - 63 points
21:42:57 < Nick_Cntdn> joelr__ - 50 points
21:42:58 < Nick_Cntdn> game over

**Comment by jes** [comment]
fixed
